# This is a basic workflow to help you get started with Actions

name: Hello

on: push

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - name: Step ONE- Print Hello World
        env:
          MY_VAR: Hi there! My name is
          FIRST_NAME: Peter
          LAST_NAME: Pan
        run: |
          echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
